title: SEHS Engineering
email: amortimer@sehs.net
description: >-
  Course content for engineering. Learn computer science, electrical engineering, design, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sehs.dev"
github_username:  agmortimer20

theme: jekyll-dash
# plugins:
#   - 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
